data_directory_on_host: "../../data"

training_labels_directory: "/data/berkeley_driving_dataset/bdd100k/labels/bdd100k_labels_images_train.json"
training_images_directory: "/data/berkeley_driving_dataset/bdd100k/images/100k/train"
training_segmentations_directory: "/data/berkeley_driving_dataset/bdd100k/drivable_maps/labels/train"

validation_labels_directory: "/data/berkeley_driving_dataset/bdd100k/labels/bdd100k_labels_images_val.json"
validation_images_directory: "/data/berkeley_driving_dataset/bdd100k/images/100k/val"
validation_segmentations_directory: "/data/berkeley_driving_dataset/bdd100k/drivable_maps/labels/val"

models_directory_on_host: "../../data/berkeley_deep_driving_models/"
current_model_directory: "/models/current_model"

categories: [
  "background", "direct", "alternative"
]


drivable_areas_indices_to_colors_map:
  1: [80, 255, 90]
  2: [230, 160, 60]

training_image_dimensions:
  width: 640
  height: 384


batch_size: 8

# Address from app container at which mlflow server can be reached
mlflow_tracking_uri: "http://deep_drive_mlflow:5000"

training_metrics_log_path: "/tmp/training_metrics.txt"

drive_recoder_movie_path: "/data/drive_recorder/chatan_2020_11_29.mp4"
drive_recoder_predictions_movie_path: "/data/drive_recorder/chatan_2020_11_29_predictions.mp4"
