data_directory_on_host: "../../data"

images_directory: "/data/berkeley_driving_dataset/bdd100k/images/"
validation_labels_directory: "/data/berkeley_driving_dataset/bdd100k/labels/bdd100k_labels_images_val.json"
