version: '3.7'
services:
    nginx:
        container_name: "deep_drive_nginx"
        image: "nginx:1.19.2"
        # Run container on default docker network
        network_mode: bridge
        ports:
            - "8080:80"
        volumes:
            - log_data:/usr/share/nginx/html

    mlflow:
        container_name: "deep_drive_mlflow"
        image: "larribas/mlflow:1.9.1"
        command: --host 0.0.0.0 --backend-store-uri file:///data
        ports:
            - "5050:5000"
        volumes:
            - mlflow_data:/data

volumes:
    log_data:
    mlflow_data:
